import {
  listChallengeRoots,
  loadChallengeSummary,
  type ChallengeSummary,
} from "./loader";
import type { ChallengeStore } from "./store/types";
import type { ChallengeMeta, Runtime } from "../../../challenges/_schema";

/**
 * The challenge index, precomputed. Lets the registry warm its whole meta tier
 * from a single read (`index.json`) instead of listing the store and reading
 * every challenge's `meta.json` — the difference between one request and dozens
 * against a remote store.
 *
 * Generated by `scripts/build-manifest.ts` (local `challenges/` tree) and, in a
 * later PR, by the Supabase seed script. When absent, the registry falls back
 * to listing + per-challenge reads, so a manifest is an optimization, never a
 * requirement.
 */

/** Where the manifest lives, relative to the store root. */
export const MANIFEST_PATH = "index.json";

/**
 * One challenge's entry: its resolved {@link ChallengeSummary} plus the
 * store-relative `path` of its root. `path` is layout-specific (the flat
 * `<slug>` for the local tree, `<difficulty>/<slug>` for the bucket), so the
 * registry reads `path` and never has to know the layout.
 */
export interface ChallengeManifestEntry extends ChallengeSummary {
  path: string;
}

export interface ChallengeManifest {
  /** Generation timestamp (ISO 8601); also the cache-busting version key. */
  version: string;
  challenges: ChallengeManifestEntry[];
}

/**
 * Build a manifest by reading every challenge summary from `store`. `pathFor`
 * maps a challenge to the store-relative root path the manifest should record
 * (defaults to the root it was read from — correct for a same-layout store; the
 * bucket seed overrides it to `<difficulty>/<slug>`).
 */
export async function buildManifest(
  store: ChallengeStore,
  pathFor: (root: string, summary: ChallengeSummary) => string = (root) => root,
): Promise<ChallengeManifest> {
  const roots = await listChallengeRoots(store);
  const challenges = await Promise.all(
    roots.map(async (root) => {
      const summary = await loadChallengeSummary(store, root);
      return { path: pathFor(root, summary), ...summary };
    }),
  );
  // Sort by slug so the manifest (and the listings it drives) is deterministic.
  challenges.sort((a, b) => a.slug.localeCompare(b.slug));
  return { version: new Date().toISOString(), challenges };
}

/** Serialize a manifest to the JSON text stored at {@link MANIFEST_PATH}. */
export function serializeManifest(manifest: ChallengeManifest): string {
  return JSON.stringify(manifest, null, 2) + "\n";
}

/** Parse + shallowly validate manifest JSON. Throws with a clear message. */
export function parseManifest(raw: string): ChallengeManifest {
  let data: unknown;
  try {
    data = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Invalid manifest JSON: ${(err as Error).message}`);
  }
  if (!data || typeof data !== "object") {
    throw new Error("Manifest must be a JSON object");
  }
  const { version, challenges } = data as Record<string, unknown>;
  if (typeof version !== "string") {
    throw new Error("Manifest.version must be a string");
  }
  if (!Array.isArray(challenges)) {
    throw new Error("Manifest.challenges must be an array");
  }
  challenges.forEach((c, i) => {
    const e = c as Record<string, unknown>;
    if (
      typeof e.slug !== "string" ||
      typeof e.path !== "string" ||
      !Array.isArray(e.languages) ||
      typeof e.defaultLanguage !== "string" ||
      !e.meta ||
      typeof e.meta !== "object"
    ) {
      throw new Error(`Manifest.challenges[${i}] is malformed`);
    }
  });
  return data as ChallengeManifest;
}

// Re-exported so callers building an index off a manifest have the field types.
export type { ChallengeMeta, Runtime };
